# Generated by Django 5.1.1 on 2024-12-02 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('work_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiftsApp.shifttype')),
            ],
        ),
    ]
