# Generated by Django 5.1.1 on 2025-01-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftsApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyshift',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlyshift',
            name='work_date',
            field=models.DateField(null=True),
        ),
    ]
